spring.application.name=api
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/symptom_witch}
spring.datasource.username=${DATABASE_USER:symptom_witch}
spring.datasource.password=${DATABASE_PASSWORD:symptom_witch}
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
